// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt7LDJilg6G7i3dJgY2QESCN04pw46rUQ',
    appId: '1:739390893230:web:3c9ac4b0ea065fa35e113f',
    messagingSenderId: '739390893230',
    projectId: 'github-service-3645c',
    authDomain: 'github-service-3645c.firebaseapp.com',
    storageBucket: 'github-service-3645c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVP3ADogpG_rgbVThg0C7lW1E1sTmdmeg',
    appId: '1:739390893230:android:498ef92f47f5e8805e113f',
    messagingSenderId: '739390893230',
    projectId: 'github-service-3645c',
    storageBucket: 'github-service-3645c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBwLis9T3iwuApJXgUvUCkMrMH5tTTXh4',
    appId: '1:739390893230:ios:5ae168b4b996a5565e113f',
    messagingSenderId: '739390893230',
    projectId: 'github-service-3645c',
    storageBucket: 'github-service-3645c.appspot.com',
    iosClientId: '739390893230-bddiedpbv31k3bqtn2c96e2vuajj0sg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.githubService',
  );
}
